Turkish translation was created
retext-project/retext pull request #556
Opened 2021-04-17 20:30 UTC by serkan-maker

I finished the translation in Transifex. Can you check it?

2021-04-18 18:31 UTC, mitya57 requested changes
Thank you very much for your translation!

I usually grab translations from Transifex before every release (or once in a few months), but as you submitted a PR, I will review it here. Left some comments.

2021-04-18 18:31 UTC, mitya57 commented on locale/retext_tr.ts
> +        <translation>&apos;% S&apos; dosyası mevcut değil.
```suggestion
        <translation>&apos;%s&apos; dosyası mevcut değil.
```

2021-04-18 18:31 UTC, mitya57 commented on locale/retext_tr.ts
> +        <translation>ReText %s (using PyMarkups %s)</translation>
Here you can translate the word ‘using’.

2021-04-18 18:31 UTC, mitya57 commented on locale/retext_tr.ts
> +        <translation>Son değişiklikten bu yana yazma yok (geçersiz kılmak için! Ekleyin)</translation>
Here the string means that one should literally type an exclamation mark. Did you translate it correctly? It is suspicious to me that `Ekleyin` is capitalized. And maybe add a space before `!`?

2021-04-18 18:49 UTC, serkan-maker commented
Thank you for this program. yes you are right the translation is wrong. i applied the fix, now i install it.
[retext_tr.ts.zip](https://github.com/retext-project/retext/files/6331974/retext_tr.ts.zip)

2021-04-18 18:58 UTC, mitya57 approved these changes
Thank you! Now it looks good, I will merge it a bit later.

2021-04-19 17:37 UTC, merged

2021-04-19 17:50 UTC, mitya57 commented
Merged, thanks again. Now I am looking at the translation in desktop file.

It currently says:

> Markdown ve Yeniden Yapılandırılmış Metin için basit ama güçlü düzenleyici

Do you think reStructuredText should be translated? It is a proper name, not two words. See <https://en.wikipedia.org/wiki/ReStructuredText>.

So maybe better to make it “Markdown ve reStructuredText için basit ama güçlü düzenleyici”?

Or just “Markdown ve reStructuredText için basit düzenleyici”, as “but powerful” was not part of the original string here.

2021-04-19 18:01 UTC, serkan-maker commented
I corrected in transifex

2021-04-19 18:06 UTC, mitya57 commented
Applied in b39ad26a32a4930b. Thanks.